services:
  - type: web
    name: majesty-compucare-limited
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://majesty-compucare-limited.onrender.com
      - key: NEXTAUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_SHORTCODE
        sync: false
      - key: MPESA_CALLBACK_URL
        value: https://majesty-compucare-limited.onrender.com/api/mpesa/callback
